apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vacation-planner-backup
  namespace: vacation-planner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
