# Generated by Django 6.0.5 on 2026-05-07 14:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lodging', models.CharField(blank=True, max_length=200)),
                ('excursion', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('airfare', 'Airfare'), ('lodging', 'Lodging'), ('meals', 'Meals'), ('excursions', 'Excursions'), ('gas', 'Gas'), ('misc', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='planner.day')),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('review', 'In Review'), ('booked', 'Booked'), ('taken', 'Taken')], default='review', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('airfare_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lodging_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('meals_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('excursions_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gas_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('misc_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('airfare_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lodging_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('meals_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('excursions_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gas_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('misc_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.vacation'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('vacation', 'date')},
        ),
    ]
