# Generated by Django 6.0.5 on 2026-05-07 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='car_rental_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vacation',
            name='car_rental_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vacation',
            name='cruise_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vacation',
            name='cruise_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('airfare', 'Airfare'), ('lodging', 'Lodging'), ('meals', 'Meals'), ('excursions', 'Excursions'), ('gas', 'Gas'), ('cruise', 'Cruise'), ('car_rental', 'Car Rental'), ('misc', 'Miscellaneous')], max_length=30),
        ),
    ]
