# Generated by Django 6.0.5 on 2026-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_vacation_car_rental_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
