# Generated by Django 6.0.5 on 2026-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_vacation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='rating',
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
