# Generated by Django 6.0.5 on 2026-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_vacationsavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationsavings',
            name='monthly_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
