# Generated by Django 6.0.5 on 2026-05-08 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_vacationsavings_monthly_contribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
