# Generated by Django 6.0.5 on 2026-05-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_family_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='journal',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DayPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='planner.day')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
