# Generated by Django 6.0.5 on 2026-05-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_journal_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='journal',
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='planner.day')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
